In [2]:
# Import required libraries

import pandas as pd
import numpy as np

In [3]:
# Load the dataset

df = pd.read_csv("tmdb_5000_movies.csv")

# Display first 5 rows
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
# Dataset shape

print("Dataset Shape:", df.shape)

# Column names

print("\nColumn Names:")
print(df.columns)

# First 5 rows

print("\nFirst 5 Rows:")
print(df.head())

# Dataset information

print("\nDataset Information:")
print(df.info())

# Missing values

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape: (4803, 20)

Column Names:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

First 5 Rows:
      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...
3  [{"name": "Legendary Pictures", "id": 923}, {"...
4        [{"name": "Walt Disney Pictures", "id": 2}]

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title  vote_average  vote_count
0                                    Avatar           7.2       11800
1  Pirates of the Caribbean: At World's End           6.9        4500
2                                   Spectre           6.3        4466
3                     The Dark Knight Rises           7.6        9106
4                               John Carter           6.1        2124

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB
None

Missing Values:
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [5]:
# Text column used for recommendation

text_column = "overview"

print("Text column selected for recommendation:", text_column)

Text column selected for recommendation: overview

In [6]:
# Import required libraries for text preprocessing

import re
import string
import nltk
from nltk.corpus import stopwords

In [7]:
# Download stopwords

nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /Users/nidhi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
# Function to clean text

def clean_text(text):
    
    # Handle missing values
    if pd.isnull(text):
        return ""
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))
    
    # Remove numbers
    text = re.sub(r"\d+", "", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    # Remove stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]
    
    return " ".join(words)

In [9]:
# Apply preprocessing to overview column

df["clean_overview"] = df["overview"].apply(clean_text)

# Display original and cleaned text

df[["overview", "clean_overview"]].head()

,overview,clean_overview
0,"In the 22nd century, a paraplegic Marine is di...",nd century paraplegic marine dispatched moon p...
1,"Captain Barbossa, long believed to be dead, ha...",captain barbossa long believed dead come back ...
2,A cryptic message from Bond’s past sends him o...,cryptic message bond’s past sends trail uncove...
3,Following the death of District Attorney Harve...,following death district attorney harvey dent ...
4,"John Carter is a war-weary, former military ca...",john carter warweary former military captain w...

In [10]:
# Check missing values after preprocessing

print(df["clean_overview"].isnull().sum())

# Display first 5 cleaned rows

df[["title", "clean_overview"]].head()

0

,title,clean_overview
0,Avatar,nd century paraplegic marine dispatched moon p...
1,Pirates of the Caribbean: At World's End,captain barbossa long believed dead come back ...
2,Spectre,cryptic message bond’s past sends trail uncove...
3,The Dark Knight Rises,following death district attorney harvey dent ...
4,John Carter,john carter warweary former military captain w...

In [11]:
# ==========================================================
# Task 3: Convert Text into Numerical Features using TF-IDF
# ==========================================================

# Import TF-IDF Vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
# Create TF-IDF Vectorizer

tfidf = TfidfVectorizer(max_features=5000)

In [13]:
# Convert cleaned movie descriptions into TF-IDF matrix

tfidf_matrix = tfidf.fit_transform(df["clean_overview"])

In [14]:
# Display the shape of TF-IDF matrix

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (4803, 5000)

In [15]:
# Display first few feature names

feature_names = tfidf.get_feature_names_out()

print(feature_names[:20])

['aaron' 'abandoned' 'abandons' 'abducted' 'abilities' 'ability' 'able'
 'aboard' 'abroad' 'absence' 'abuse' 'abused' 'abusive' 'academic'
 'academy' 'accept' 'accepted' 'accepts' 'access' 'accident']

In [16]:
# ==========================================================
# Task 4: Calculate Cosine Similarity
# ==========================================================

# Import cosine similarity

from sklearn.metrics.pairwise import cosine_similarity

In [17]:
# Calculate cosine similarity matrix

similarity_matrix = cosine_similarity(tfidf_matrix)

In [18]:
# Display the shape of similarity matrix

print("Similarity Matrix Shape:", similarity_matrix.shape)

Similarity Matrix Shape: (4803, 4803)

In [19]:
# Display similarity scores of the first movie

print(similarity_matrix[0])

[1. 0. 0. ... 0. 0. 0.]

In [20]:
# Display similarity score between first and second movie

print("Similarity Score:", similarity_matrix[0][1])

Similarity Score: 0.0

In [21]:
# ==========================================================
# Task 5: Build Movie Recommendation Function
# ==========================================================

# Function to recommend similar movies

def recommend_movies(movie_name):
    
    # Check if movie exists
    if movie_name not in df["title"].values:
        print("Movie not found in the dataset.")
        return

    # Get movie index
    movie_index = df[df["title"] == movie_name].index[0]

    # Get similarity scores
    similarity_scores = list(enumerate(similarity_matrix[movie_index]))

    # Sort movies based on similarity
    sorted_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    print("Recommended Movies:\n")

    count = 0

    for movie in sorted_movies[1:]:
        index = movie[0]
        print(df.iloc[index]["title"])

        count += 1

        if count == 5:
            break

In [22]:
# Test 1

recommend_movies("Avatar")

Recommended Movies:

Apollo 18
The American
The Inhabited Island
Tears of the Sun
The Adventures of Pluto Nash

In [23]:
# Test 2

recommend_movies("Batman Begins")

Recommended Movies:

Batman Returns
The Dark Knight
Batman
The Dark Knight Rises
Batman Forever

In [24]:
# Test 3

recommend_movies("The Dark Knight")

Recommended Movies:

The Dark Knight Rises
Batman Returns
Batman Forever
Batman: The Dark Knight Returns, Part 2
Batman Begins

In [25]:
# Test with an invalid movie name

recommend_movies("ABC Movie")

Movie not found in the dataset.